In [3]:
import json
import pandas as pd
import MeCab

In [4]:
stories_json = []
with open('./output_storiesv3.json', 'r') as f:
    stories_json = stories_json + json.loads(f.read())

print(len(stories_json))
print(stories_json[1].keys())

529
dict_keys(['index', 'title', 'broadcasting_date', 'abstracts_list'])

In [5]:
stories_df = pd.DataFrame(stories_json)
stories_df["abstract_joined"] = stories_df["abstracts_list"].str.join(" ")
stories_df.head()

,index,title,broadcasting_date,abstracts_list,abstract_joined
0,0325,2013年3月15日放送,2013年3月15日,[何をやってもうまくいかないのび太は、「魔法（まほう）が使えたら便利で楽しくなるにちがいない...,何をやってもうまくいかないのび太は、「魔法（まほう）が使えたら便利で楽しくなるにちがいない」...
1,0326,2013年4月12日放送,2013年4月12日,[ある朝、ねぼうしたのび太に泣きつかれたドラえもんは、『ばくはつコショウ』を取り出す。このコ...,ある朝、ねぼうしたのび太に泣きつかれたドラえもんは、『ばくはつコショウ』を取り出す。このコシ...
2,0327,2013年4月26日放送,2013年4月26日,[スネ夫からハワイ旅行をじまんされたのび太は、自分もハワイに行きたいとママにたのもうとするが...,スネ夫からハワイ旅行をじまんされたのび太は、自分もハワイに行きたいとママにたのもうとするが、...
3,0328,2013年5月3日放送,2013年5月3日,[のび太とドラえもんが部屋で昼寝をしていると、突然大きな音が聞こえてくる。となりの家が改築工...,のび太とドラえもんが部屋で昼寝をしていると、突然大きな音が聞こえてくる。となりの家が改築工事...
4,0329,2013年5月10日放送,2013年5月10日,[そうじにせんたく、町内会の会合と毎日大忙しのママが、「体がもうひとつほしい」とため息をつい...,そうじにせんたく、町内会の会合と毎日大忙しのママが、「体がもうひとつほしい」とため息をついて...

In [6]:
t = MeCab.Tagger('-d /opt/homebrew/lib/mecab/dic/mecab-ipadic-neologd')
def mecab_tokenizer(text):
    parsed_lines = t.parse(text).split("\n")[:-2]
    surfaces = [l.split('\t')[0] for l in parsed_lines]
    features = [l.split('\t')[1] for l in parsed_lines]
    # 原型を取得
    bases = [f.split(',')[6] for f in features]
    # 品詞を取得
    pos = [f.split(',')[0] for f in features]

    # 各単語を原型に変換する
    token_list = [b if b != '*' else s for s, b in zip(surfaces, bases)]
    # 品詞を絞り込み
    target_pos = ["名詞"]
    token_list = [t for t, p in zip(token_list, pos) if p in target_pos]
    # アルファベットを小文字に統一
    token_list = [t.lower() for t in token_list]

    return [ text for text in filter(lambda x: not x.isascii(), token_list)]

wt = MeCab.Tagger('-Owakati')
def mecab_tokenizer_wakachi(text):
    return wt.parse(text).split(" ")

In [7]:
# ストーリーが取得できたものに絞る
stories_df = stories_df[stories_df['abstract_joined'].str.len() > 0] 
sentences = stories_df["abstract_joined"].apply(mecab_tokenizer_wakachi).apply(set).apply(list)
print(sentences)
print(sentences)

0      [ある, ”, けん, スケール, しん, 最新, 使え, りゃく, た, 変え, 聞い, ...
1      [ある, 使っ, 朝, 地, すむ, 会社, た, まで, 聞き, 花見, かし, まくる,...
2      [すぎ, 強要, どう, おじいさん, 山菜, きびしい, た, まで, 得, 高く, 10...
3      [使っ, はげ, のんびり, もう, カンタン, 追いかけ, 使う, くさい, すむ, どち...
4      [ある, スーツ, 育て, 手, もう, 近づい, た, 探し求め, 聞き, 聞い, すませ...
                             ...
524    [使っ, 手, ょう, こわれ, どちら, た, 変え, 古い, 聞い, おかし, 杉, お...
525    [ささる, ある, 手, 食べ, 焼き, どう, うち, た, まで, もうかれ, 話し出し...
526    [すぎ, 手, ”, すいこま, 光り, ふだん, 人気, た, まで, よう, 聞い, ア...
527    [使っ, ”, ょう, けん, のんびり, まるで, ヴィルトゥオーゾ, どう, 良い, う...
528    [帰っ, ある, ”, とたん, よばわり, 野菜, 食べ, かざっ, た, やってき, 興...
Name: abstract_joined, Length: 529, dtype: object
0      [ある, ”, けん, スケール, しん, 最新, 使え, りゃく, た, 変え, 聞い, ...
1      [ある, 使っ, 朝, 地, すむ, 会社, た, まで, 聞き, 花見, かし, まくる,...
2      [すぎ, 強要, どう, おじいさん, 山菜, きびしい, た, まで, 得, 高く, 10...
3      [使っ, はげ, のんびり, もう, カンタン, 追いかけ, 使う, くさい, すむ, どち...
4      [ある, スーツ, 育て, 手, もう, 近づい, た, 探し求め, 聞き, 聞い, すませ...
                             ...
524    [使っ, 手, ょう, こわれ, どちら, た, 変え, 古い, 聞い, おかし, 杉, お...
525    [ささる, ある, 手, 食べ, 焼き, どう, うち, た, まで, もうかれ, 話し出し...
526    [すぎ, 手, ”, すいこま, 光り, ふだん, 人気, た, まで, よう, 聞い, ア...
527    [使っ, ”, ょう, けん, のんびり, まるで, ヴィルトゥオーゾ, どう, 良い, う...
528    [帰っ, ある, ”, とたん, よばわり, 野菜, 食べ, かざっ, た, やってき, 興...
Name: abstract_joined, Length: 529, dtype: object

In [8]:
print(stories_df[stories_df["abstract_joined"].str.contains("凶悪")]["abstract_joined"])

50    今日はドラえもんの誕生日。ドラえもんをおどろかせるようなものをプレゼントしたいと考えたのび太...
Name: abstract_joined, dtype: object

In [9]:
keywords_dict = {}
for keyword_list in sentences.tolist():
    for keyword in keyword_list:
        if (keyword not in keywords_dict): keywords_dict[keyword] = 1
        else: keywords_dict[keyword] = keywords_dict[keyword] + 1

keywords_df = pd.DataFrame([{
    "key": key,
    "val": val
} for key,val in keywords_dict.items()])
keywords_df = keywords_df.sort_values("val", ascending=False)

In [10]:
pd.set_option('display.max_rows', 500)
keywords_df

          key  val
123         、  529
20          と  529
79          は  529
110         の  529
118        \n  529
...       ...  ...
7477       和食    1
7476      見直さ    1
7475       送信    1
7474   パワーアップ    1
10761      戯画    1

[10762 rows x 2 columns]

In [ ]:
keywords_df.to_csv('doraemon-word-frequencies.csv')

In [12]:
keywords_df.head()

    key  val
123   、  529
20    と  529
79    は  529
110   の  529
118  \n  529